
server:
  port: 8070
#  ssl:
#    key-store: classpath:mydomain_com.p12
#    src/main/resources/mydomain_com.p12
#    key-store-password: 1203
#    key-store-type: PKCS12
#    key-alias: mydomain
#    key-password: 1203

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms
#    ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}

    drive-class-name: org.mariadb.jdbc.Driver
    username: root
    password: A@12032001
#    ${MYSQL_ROOT_PASSWORD:A@12032001}
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 20000
#      pool-name: HikariCP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size : 100MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  data:
    redis:
      #spring.data.redis.use-redis-cache
      use-redis-cache: false
      host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
      #host: ${REDIS_HOST:ubuntu-server-01.local} # Default to 'localhost' if not provided
      port: ${REDIS_PORT:6379}      # Default to 6379 if not provided
  mail:
    host: smtp.gmail.com
    port: 587
    username: staff.zen03@gmail.com
    password: lmqe qsfl vhkd ifoj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8


api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey : teSMQiQ2xl1+Qk8BojRzwg7e9NefjFxabx5eA1+15Is=
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60

# Đường dẫn đến thư mục lưu trữ hình ảnh
upload:
  dir: E:\Git\Github\hrms\sys\upload

logging:
  level:
    org.springframework: INFO
#    com.zaxxer.hikari: DEBUG
